config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :motos do
    member do
      resources :bookings
    end
  end
  get "dashboard", to: "dashboards#show", as: :dashboard
  patch "bookings/:id/accept", to: "bookings#accept", as: :booking_accept
  patch "booking/:id/decline", to: "bookings#decline", as: :booking_decline
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :moto
  belongs_to :user
end

app/models/moto.rb
class Moto < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  include PgSearch::Model
  pg_search_scope :search_by_model_and_adress,
    against: [ :model, :address, :brand ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :motos, dependent: :destroy
  has_one_attached :photo
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def find_bookings
    Booking.joins(:moto).where("motos.user_id = #{id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :phone_number, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :phone_number, :photo])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @moto = Moto.find(params[:id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.moto = Moto.find(params[:id])
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def accept
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "Accepté"
    @booking.save
    redirect_to dashboard_path(anchor: "booking-#{@booking.id}")
  end

  def decline
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.status = "Décliné"
    @booking.save
    redirect_to dashboard_path(anchor: "booking-#{@booking.id}")
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @bookings_send = current_user.bookings
    @motos = Moto.where(user: current_user)
    @bookings_rec = current_user.find_bookings
    authorize @bookings_send
    authorize @bookings_rec
    authorize @motos
  end
end

app/controllers/motos_controller.rb
class MotosController < ApplicationController
  before_action :set_moto, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @motos = policy_scope(Moto).order(created_at: :desc)

    if params[:query].present?
      @motos = Moto.search_by_model_and_adress(params[:query])
    end
  end

  def new
    @moto = Moto.new
    authorize @moto
  end

  def create
    @moto = Moto.new(moto_params)
    @moto.user = current_user
    authorize @moto
    if @moto.save
      redirect_to motos_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    authorize @booking
    authorize @moto
    @marker = {
        lat: @moto.latitude,
        lng: @moto.longitude,
        image_url: helpers.asset_url("marker.png")
      }
  end

  def edit
    authorize @moto
  end

  def update
    authorize @moto
    @moto.update(moto_params)
    if @moto.save
      redirect_to moto_path(@moto)
    else
      render :edit
    end
  end

  def destroy
    authorize @moto
    @moto.destroy
    redirect_to dashboard_path
  end

  private

  def moto_params
    params.require(:moto).permit(:model, :brand, :cylinder, :price, :photo, :address)
  end

  def set_moto
    @moto = Moto.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @motos = Moto.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<%@bookings.each do |booking| %>
<h1><%= booking.moto.model%></h1>
<h2><%= booking.moto.brand %></h2>
<p>Du : <%= booking.start_date %></p>
<p>Au : <%= booking.end_date %></p>
<%end %>

app/views/bookings/new.html.erb
<div class="container text-center">
  <h1>Réserver votre 2 roues</h1>
  <%= image_tag @moto.photo, style:"height: 500px" %>
  <h2><%= @moto.model %></h2>
  <h3><%= @moto.brand %></h3>
  <%= simple_form_for(@booking) do |f| %>
    <%= f.input :start_date, as: :date, label: "Du" , html5: true%>
    <%= f.input :end_date, as: :date, label: "Au", html5: true %>
    <%= f.submit class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container text-center">
  <h1>Votre réservation a bien été prise en compte</h1>
  <%= image_tag @booking.moto.photo, style:"height: 500px" %>
  <h2><%= @booking.moto.model %></h2>
  <h3><%= @booking.moto.brand %></h3>
  <p>Par : <%= image_tag @booking.moto.user.photo, class: "avatar" %><%= @booking.moto.user.first_name %></p>
  <p>Du : <%= @booking.start_date %> Au : <%= @booking.end_date %></p>
  <p>En attente de validation</p>
  <h2><strong>Prix total: <%= @booking.moto.price * (@booking.end_date - @booking.start_date) %> €</strong></h2>
  <%= link_to "Dashboard", dashboard_path, class: "btn btn-blue" %>
  <%= link_to "Retour à l'accueil", root_path, class: "btn btn-grey" %>
</div>

app/views/dashboards/show.html.erb
<div class="container">
  <h1>Mon dashboard</h1>
  <div class="my-3">
    <h2 class="mb-3">Mes demandes envoyées</h2>
    <div class="row justify-content-between">
      <%@bookings_send.each do |booking| %>
        <div class="card col-lg-3 my-3" style="width: 18rem;">
          <%= image_tag booking.moto.photo, class:"card-img-top card-dashboard mt-2" %>
          <div class="card-body">
            <h5 class="card-title"><%= "#{booking.moto.brand} #{booking.moto.model}"%></h5>
            <p class="card-text">Loué par <%= booking.moto.user.first_name %> <%=image_tag booking.moto.user.photo, class:"avatar", style: "width: 30px; height: 30px" %></p>
            <div class="p-1">
              <p>Du <%= booking.start_date %></p>
              <p>Au <%= booking.end_date %></p>
            </div>
            <% case booking.status %>
            <% when "En attente" %>
              <p class="btn btn-grey w-100"><%= booking.status %></p>
            <% when "Accepté"%>
              <p class="btn btn-blue w-100"><%= booking.status %></p>
            <% when "Décliné"%>
              <p class="btn btn-red w-100"><%= booking.status %></p>
            <% end %>
          </div>
        </div>
      <%end %>
    </div>
  </div>
  <div class="my-3">
    <h2 class="mb-3">Mes offres</h2>
    <div class="row justify-content-between">
      <%@motos.each do |moto| %>
        <div class="card col-lg-3 my-3" style="width: 18rem;">
          <%= image_tag moto.photo, class:"card-img-top card-dashboard mt-2" %>
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <h5 class="card-title"><%= "#{moto.brand} #{moto.model}"%></h5>
              <p><%= moto.price.to_i%> €</p>
            </div>
            <%= link_to "Modifier", edit_moto_path(moto), class: "btn btn-grey" %>
            <%= link_to "Supprimer", moto_path(moto), method: :delete, data: { confirm: "Are you sure you want to remove #{moto.brand}"},class: "btn btn-red", remote: true %>
          </div>
        </div>
      <%end %>
    </div>
  </div>
  <div class= "my-3">
    <h2 class="mb-3">Mes demandes reçues</h2>
    <div class="row justify-content-between">
      <%@bookings_rec.each do |booking| %>
        <div class="card col-lg-3" style="width: 18rem" id="booking-<%=booking.id%>">
          <%= image_tag booking.moto.photo, class:"card-img-top card-dashboard mt-2" %>
          <div class="card-body" ">
            <h5 class="card-title"><%= "#{booking.moto.brand} #{booking.moto.model}"%></h5>
            <p class="card-text">Demandé par <%= booking.user.first_name %> <%=image_tag booking.user.photo, class:"avatar", style: "width: 30px; height: 30px" %></p>
            <div class="p-1">
              <p>Du <%= booking.start_date %></p>
              <p>Au <%= booking.end_date %></p>
            </div>
            <p><%= booking.status %></p>
            <% if booking.status == "En attente" %>
              <%= link_to "Accepter", booking_accept_path(booking), method: :patch, class: "btn btn-grey", remote: true %>
              <%= link_to "Décliner", booking_decline_path(booking), method: :patch, class: "btn btn-red", remote: true %>
            <% end %>
          </div>
        </div>
      <%end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Road2wheels</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="shortcut icon" href="/assets/favicon.png" />

  </head>

  <body>
    <%= render './shared/navbar' %>
    <div style="min-height:80vh">

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    </div>
    <footer>
      <%= render partial: "shared/footer"  %>
    </footer>
  </body>
</html>

app/views/motos/edit.html.erb
<div class="container">
  <%= simple_form_for(@moto) do |f| %>
    <%= f.input :brand %>
    <%= f.input :model %>
    <%= f.input :cylinder %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/motos/index.html.erb
<div class="container">
  <h1 class="text-center" style="margin-top: 16px">Toutes nos motos</h1>
  <br>
    <%= link_to "Ajouter une offre", new_moto_path, class: "btn btn-blue" %>
  <br>

  <div class="row justify-content-between">
    <%@motos.each do |moto| %>
      <div class="card col-4 mt-5 position-relative" style="width: 24rem; ">
        <%= image_tag moto.photo, alt: moto.brand, class:"card-img-top mt-2", style:"height: 250px" %>
        <div class="card-body">
          <h5 class="card-title w-100 text-decoration-none"><%= moto.brand %></h5>
          <h3 class="card-text"><%= moto.model %></h3>
          <h3 class="card-text"><%= moto.address %></h3>
          <h5 class="card-price position-absolute bottom-0 end-0 mx-2 "><%= moto.price.to_i%>€/jour</h5>

          <a class="stretched-link" href="/motos/<%= moto.id %>"></a>
          <%# <%= link_to moto_path(moto), class: "" %>
          <%# <%= link_to "Détails de l'offre", moto_path(moto),class: "btn btn-info w-100" %>
          <%# <%= link_to "Edit", edit_moto_path(moto),class: "btn btn-primary" %>
          <%# <%= link_to "Delete", moto_path(moto), method: :delete, data: { confirm: "Are you sure you want to remove #{moto.brand}"},class: "btn btn-danger" %>
        </div>
      </div>
    <%end %>
  </div>
</div>

app/views/motos/new.html.erb
<div class="container">
  <h1>Louez votre 2 roues</h1>
  <%= simple_form_for(@moto) do |f| %>
    <%= f.input :brand, placeholder: 'example : Honda', label: 'Marque' %>
    <%= f.input :model, placeholder: 'example : CBF', label: 'Modèle' %>
    <%= f.input :cylinder, placeholder: '650', label: 'Cylindre' %>
    <%= f.input :address, placeholder: '1, rue des pots', label: 'Addresse' %>
    <%= f.input :price, placeholder: 'example : 60.50', label: 'Prix/jour' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Créer', class: "btn btn-blue"%>
  <% end %>
</div>

app/views/motos/show.html.erb
<div class="container">
    <div class=" card-product mt-4 ">
      <div class="row ">
      <div class="col-lg-6 col-12">
        <%= image_tag @moto.photo, alt: @moto.brand, class:"card-img-top card-product-img", style:"width: 100%" %>
      </div>
      <div class="col-lg-6 col-12 ">
        <div class="card-product-infos">
          <h1><strong><%= @moto.brand%></strong> <%= @moto.model %></h1>
          <h2><%= @moto.cylinder %> cc</h2>
          <h2><%= @moto.address %></h2>
          <h2><strong><%= @moto.price.to_i %> €/jour</strong></h2>
          <h2><%= image_tag @moto.user.photo, class: "avatar" %><%= @moto.user.first_name %></h2>
          <% if current_user == @moto.user  %>
              <%= link_to "Edit", edit_moto_path(@moto),class: "btn btn-grey mt-4 mx-2", style: "width: 46%" %>
              <%= link_to "Delete", moto_path(@moto), method: :delete, data: { confirm: "Are you sure you want to remove #{@moto.brand}"},class: "btn btn-red mt-4 mx-2", style: "width: 46%" %>
          <% else %>
            <p><%= link_to "Réserver", moto_path(@moto, anchor: "form"), class:"btn btn-blue w-100 mt-4" %></p>
          <% end  %>
        </div>
        <div class="p-3">
          <div style="width: 100%; height: 300px; margin-top: 8px; "
            data-controller="mapbox"
            data-mapbox-marker-value="<%= @marker.to_json %>"
            data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>
    </div>
  </div>
  <% if current_user != @moto.user  %>
  <div class="container text-center mt-4" id="form">
    <h1>Réserver votre 2 roues</h1>
    <div class="container" style="width: 50%">
      <%= simple_form_for(@booking) do |f| %>
      <%= f.input :start_date, as: :date, label: "Du", html5: true %>
      <%= f.input :end_date, as: :date, label: "Au", html5: true %>
      <%= f.submit "Réserver" ,class: "btn btn-blue w-50" %>
      <% end %>
    </div>
  </div>
  <% end  %>
</div>

app/views/pages/home.html.erb
<%= render './shared/banner' %>

<div class="container">
  <h1 class="text-center my-3">Les dernières offres</h1>
  <%= render './shared/cards' %>
</div>

app/views/shared/_banner.html.erb
<div class="row justify-content-center">
    <div class="col-12 ">
      <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active" >
          <div class="banner" style="height: 500px; background-position: bottom; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1547906250-5bdf142c606d?crop=entropy&cs=tinysrgb&fm=[…]FyY2h8N3x8bW90b3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800)">
            <div class="carousel-caption d-none d-md-block">
              <h4>Louez le temps que vous voulez</h4>
              <p>Vacances, week-end, déplacements ponctuels, choisissez votre durée</p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="banner" style="height: 500px; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1629035888981-f0570f0e94bd?crop=entropy&cs=tinysrgb&[…]ZWFyY2h8MTJ8fG1vdG98ZW58MHx8MHx8&auto=format&fit=crop&w=800)">
            <div class="carousel-caption d-none d-md-block">
              <h4>Louez en fonction de votre trajet</h4>
              <p>Trail, Roadster, GT, Scooter</p>
            </div>
          </div>
        </div>
        <div class="carousel-item">
          <div class="banner" style="height: 500px; background-position: center; background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1623837244511-6d60815e43aa?crop=entropy&cs=tinysrgb&[…]ZWFyY2h8Mjl8fG1vdG98ZW58MHx8MHx8&auto=format&fit=crop&w=800)">
            <div class="carousel-caption d-none d-md-block">
              <h4>Louez selon votre budget</h4>
              <p>Scooter ou trail dernier cri, vous choisissez la formule qui vous convient</p>
            </div>
          </div>
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    </div>
  </div>

app/views/shared/_cards.html.erb
<div class="container">
  <div class="row  justify-content-around mb-4">
    <%Moto.all.last(3).each do |moto| %>
      <%=link_to moto_path(moto), class: "card-trip col-12 col-lg-3 pt-2 text-decoration-none text-dark" do %>
          <%= image_tag moto.photo , style:"height: 280px" %>
          <div class="card-trip-infos">
            <div>
              <h2><%= moto.model %></h2>
              <p><%= moto.brand %></p>
            </div>
            <h2 class="card-trip-pricing"><%= moto.price.to_i %>€/jour</h2>

            <%= image_tag moto.user.photo, class: "card-trip-user avatar-bordered" %>
          </div>
      <%end %>
    <%end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    made with <i class="fas fa-heart"></i> by #AmazonesTeam
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo3.png", style: "width: 300px" %>
    <% end %>
    <div>
      <%= link_to "Voir toutes nos motos", motos_path, class: "btn btn-blue" %>
    </div>
    <div class="search" >
      <div>
        <%= form_tag motos_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Chercher une moto",
            style: "border-radius: 8px"
            %>
      </div>

      <div>
          <%= submit_tag "Rechercher", class: "btn btn-blue", style: "margin-left: 5px" %>
        <% end %>
      </div>

    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%if user_signed_in? %>
          <li class="nav-item active">
             <%= link_to "Ajouter une offre", new_moto_path, class: "btn btn-outline-light mx-3" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
              <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item"-->
            <%= link_to "Se connecter", new_user_session_path, class: "btn btn-outline-light" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>